[2016-09-03 15:34:21 +0000] [4284] [INFO] Starting gunicorn 19.6.0
[2016-09-03 15:34:21 +0000] [4284] [INFO] Listening at: http://127.0.0.1:8080 (4284)
[2016-09-03 15:34:21 +0000] [4284] [INFO] Using worker: sync
[2016-09-03 15:34:21 +0000] [4289] [INFO] Booting worker with pid: 4289
[2016-09-03 15:34:21 +0000] [4289] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named wsgi
[2016-09-03 15:34:21 +0000] [4289] [INFO] Worker exiting (pid: 4289)
[2016-09-03 15:34:21 +0000] [4284] [INFO] Shutting down: Master
[2016-09-03 15:34:21 +0000] [4284] [INFO] Reason: Worker failed to boot.
[2016-09-03 15:34:29 +0000] [4298] [INFO] Starting gunicorn 19.6.0
[2016-09-03 15:34:29 +0000] [4298] [INFO] Listening at: http://127.0.0.1:8080 (4298)
[2016-09-03 15:34:29 +0000] [4298] [INFO] Using worker: sync
[2016-09-03 15:34:29 +0000] [4303] [INFO] Booting worker with pid: 4303
[2016-09-03 15:34:29 +0000] [4303] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named wsgi
[2016-09-03 15:34:29 +0000] [4303] [INFO] Worker exiting (pid: 4303)
[2016-09-03 15:34:29 +0000] [4298] [INFO] Shutting down: Master
[2016-09-03 15:34:29 +0000] [4298] [INFO] Reason: Worker failed to boot.
